name: Publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@labdigital'
      - run: yarn
      - run: yarn build
      - run: npm login
      - run: npm publish ./packages/common/dist
      - run: npm publish ./packages/plugin-json/dist
      - run: npm publish ./packages/plugin-terraform/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
